version: "3.8"

services:
  app:
    build: .
    network_mode: host

  cassandra:
    container_name: cassandra
    image: cassandra:4.1.1
    volumes:
      - /home/bruna/study/jubs-network-v2/data/cassandra
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_START_RPC=true
      - CASSANDRA_CLUSTER_NAME=PostsCluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=datacenter
