version: '3'

services:
  neo4j:
    container_name: neo4j
    image: neo4j:latest
    volumes:
      - /home/bruna/study/jubs-network-v2/data/neo4j
    ports:
      - '7474:7474'
      - '7687:7687'
    environment:
      - NEO4J_AUTH=neo4j/12345678
